import { MenuGroup } from './models';

export const POS_MENU_GROUPS: MenuGroup[] = [
  { key: 'dashboard-group', label: 'Dashboard', icon: 'pi pi-home', items: [{ key: 'dashboard', label: 'Overview', description: 'Billing, return refunds, and alerts', route: 'dashboard' }] },
  { key: 'billing-group', label: 'Billing', icon: 'pi pi-shopping-cart', items: [{ key: 'billing', label: 'Billing', description: 'Menus, cart, payment, and print bill', route: 'billing' }, { key: 'print-bills', label: 'Print Bills', description: 'Review and reprint invoices', route: 'print-bills' }] },
  { key: 'food-menu-group', label: 'Food Menu', icon: 'pi pi-box', items: [{ key: 'menus', label: 'Menus', description: 'View, edit, and delete menu items', route: 'menus' }, { key: 'categories', label: 'Categories', description: 'Manage product categories', route: 'categories' }] },
  { key: 'inventory-group', label: 'Inventory', icon: 'pi pi-warehouse', items: [{ key: 'stock-in', label: 'Stock In', description: 'Record inward stock entries', route: 'stock-in' }, { key: 'stock-out', label: 'Stock Out', description: 'Record outward stock movement', route: 'stock-out' }, { key: 'current-stock', label: 'Current Stock', description: 'View live stock by location', route: 'current-stock' }, { key: 'low-stock', label: 'Low Stock Alert', description: 'Monitor products below reorder level', route: 'low-stock' }] },
  { key: 'customers-group', label: 'Customers', icon: 'pi pi-id-card', items: [{ key: 'customers', label: 'Customer List', description: 'Add and edit customer profiles', route: 'customers' }, { key: 'customer-history', label: 'Purchase History', description: 'Review customer purchase history', route: 'customer-history' }, { key: 'credit-tracking', label: 'Credit Tracking', description: 'Track due and collections', route: 'credit-tracking' }] },
  { key: 'orders-group', label: 'Orders', icon: 'pi pi-receipt', items: [{ key: 'return-refund', label: 'Return Refund', description: 'Handle return entries and refunds', route: 'return-refund' }] },
  { key: 'payments-group', label: 'Payments', icon: 'pi pi-credit-card', items: [{ key: 'payments', label: 'Payment History', description: 'Review payment entries', route: 'payments' }, { key: 'pending-payments', label: 'Pending Payments', description: 'Track unpaid invoices', route: 'pending-payments' }] },
  { key: 'reports-group', label: 'Reports', icon: 'pi pi-chart-line', items: [{ key: 'daily-sales', label: 'Daily Sales', description: 'Track daily billing and cash flow', route: 'daily-sales' }, { key: 'monthly-sales', label: 'Monthly Sales', description: 'Monitor monthly sales performance', route: 'monthly-sales' }, { key: 'menu-sales', label: 'Menu wise Sales', description: 'See best-performing menu items', route: 'menu-sales' }] },
  { key: 'organization-group', label: 'Organization', icon: 'pi pi-building', items: [{ key: 'organization', label: 'Organization', description: 'Maintain restaurant organization details', route: 'organization' }, { key: 'branches', label: 'Branches', description: 'Manage store branches', route: 'branches' }, { key: 'counters', label: 'Counters', description: 'Manage restaurant service counters', route: 'counters' }, { key: 'terminal', label: 'Terminal', description: 'Manage POS terminals by counter', route: 'terminal' }, { key: 'printers', label: 'Printers', description: 'Configure kitchen and billing printers', route: 'printers' }] },
  { key: 'users-group', label: 'Users & Roles', icon: 'pi pi-users', items: [{ key: 'users', label: 'Users', description: 'Manage admin and staff access', route: 'users' }, { key: 'roles', label: 'Roles', description: 'Define role templates and permissions', route: 'roles' }] }
];
