import { MenuGroup } from './models';

export const POS_MENU_GROUPS: MenuGroup[] = [
  { key: 'dashboard-group', label: 'Dashboard', icon: 'pi pi-home', items: [{ key: 'dashboard', label: 'Overview', description: 'Sales, orders, and alerts', route: 'dashboard' }] },
  { key: 'sales-group', label: 'Sales', icon: 'pi pi-shopping-cart', items: [{ key: 'sales', label: 'Main POS Screen', description: 'Products, cart, payment, and print bill', route: 'sales' }, { key: 'print-bills', label: 'Print Bills', description: 'Review and reprint invoices', route: 'print-bills' }] },
  { key: 'products-group', label: 'Products', icon: 'pi pi-box', items: [{ key: 'products', label: 'Product List', description: 'View, edit, and delete products', route: 'products' }, { key: 'categories', label: 'Categories', description: 'Manage product categories', route: 'categories' }] },
  { key: 'inventory-group', label: 'Inventory', icon: 'pi pi-warehouse', items: [{ key: 'stock-in', label: 'Stock In', description: 'Record inward stock entries', route: 'stock-in' }, { key: 'stock-out', label: 'Stock Out', description: 'Record outward stock movement', route: 'stock-out' }, { key: 'current-stock', label: 'Current Stock', description: 'View live stock by location', route: 'current-stock' }, { key: 'low-stock', label: 'Low Stock Alert', description: 'Monitor products below reorder level', route: 'low-stock' }] },
  { key: 'customers-group', label: 'Customers', icon: 'pi pi-id-card', items: [{ key: 'customers', label: 'Customer List', description: 'Add and edit customer profiles', route: 'customers' }, { key: 'customer-history', label: 'Purchase History', description: 'Review customer purchase history', route: 'customer-history' }, { key: 'credit-tracking', label: 'Credit Tracking', description: 'Track due and collections', route: 'credit-tracking' }] },
  { key: 'orders-group', label: 'Orders', icon: 'pi pi-receipt', items: [{ key: 'transactions', label: 'Transactions', description: 'View all sales transactions', route: 'transactions' }, { key: 'invoice-details', label: 'Invoice Details', description: 'Inspect invoice items and totals', route: 'invoice-details' }, { key: 'returns', label: 'Returns & Refunds', description: 'Handle return entries and refunds', route: 'returns' }] },
  { key: 'payments-group', label: 'Payments', icon: 'pi pi-credit-card', items: [{ key: 'payments', label: 'Payment History', description: 'Review payment entries', route: 'payments' }, { key: 'pending-payments', label: 'Pending Payments', description: 'Track unpaid invoices', route: 'pending-payments' }] },
  { key: 'expenses-group', label: 'Expenses', icon: 'pi pi-wallet', items: [{ key: 'expenses', label: 'Expense Register', description: 'Log store expenses', route: 'expenses' }, { key: 'expense-report', label: 'Expense Report', description: 'Review monthly expense totals', route: 'expense-report' }] },
  { key: 'reports-group', label: 'Reports', icon: 'pi pi-chart-line', items: [{ key: 'daily-sales', label: 'Daily Sales', description: 'Track daily billing and cash flow', route: 'daily-sales' }, { key: 'monthly-profit', label: 'Monthly Profit', description: 'Monitor monthly revenue and profit', route: 'monthly-profit' }, { key: 'product-sales', label: 'Product-wise Sales', description: 'See best-performing items', route: 'product-sales' }, { key: 'inventory-report', label: 'Inventory Report', description: 'Review stock movement', route: 'inventory-report' }, { key: 'tax-report', label: 'Tax / GST Report', description: 'Track tax totals', route: 'tax-report' }] },
  { key: 'organization-group', label: 'Organization', icon: 'pi pi-building', items: [{ key: 'organization', label: 'Company Profile', description: 'Maintain company details', route: 'organization' }, { key: 'branches', label: 'Branches', description: 'Manage store branches', route: 'branches' }, { key: 'departments', label: 'Departments', description: 'Create departments', route: 'departments' }, { key: 'sub-departments', label: 'Sub Departments', description: 'Maintain sub-departments', route: 'sub-departments' }] },
  { key: 'users-group', label: 'Users & Roles', icon: 'pi pi-users', items: [{ key: 'users', label: 'Users', description: 'Manage admin and staff access', route: 'users' }, { key: 'roles', label: 'Roles', description: 'Define role templates', route: 'roles' }, { key: 'permissions', label: 'Permissions', description: 'Control module access', route: 'permissions' }] },
  { key: 'notifications-group', label: 'Notifications', icon: 'pi pi-bell', items: [{ key: 'notifications', label: 'Alert Center', description: 'Low stock and system alerts', route: 'notifications' }] },
  { key: 'settings-group', label: 'Settings', icon: 'pi pi-cog', items: [{ key: 'settings', label: 'App Settings', description: 'Store profile and invoice setup', route: 'settings' }] }
];
